-- Add rare spider boss materials to item_templates table
INSERT INTO item_templates (
  item_id, name, type, rarity, description, source_type, source_details, 
  image_url, value, level_requirement, drop_chance
) VALUES 
  (
    'skeleton_spider_bone',
    'Кость паука-скелета',
    'material',
    'legendary',
    'Прочная, легкая кость с магическими свойствами.',
    'boss_drop',
    '{"boss_types": ["skeleton_spider"], "drop_locations": ["necropolis", "bone_caverns"]}',
    '/src/assets/items/skeleton_spider_bone.png',
    800,
    15,
    0.05
  ),
  (
    'illusion_pollen',
    'Пыльца иллюзии',
    'material',
    'epic',
    'Мелкая пыль, искажающая восприятие.',
    'boss_drop',
    '{"boss_types": ["illusion_spider"], "drop_locations": ["dream_realm", "mystic_forest"]}',
    '/src/assets/items/illusion_pollen.png',
    600,
    12,
    0.08
  ),
  (
    'wyvern_wing',
    'Крыло виверны',
    'material',
    'epic',
    'Недоразвитое перепончатое крыло.',
    'boss_drop',
    '{"boss_types": ["wyvern_spider"], "drop_locations": ["sky_peaks", "wind_caverns"]}',
    '/src/assets/items/wyvern_wing.png',
    550,
    11,
    0.10
  ),
  (
    'hunter_claw',
    'Коготь охотника',
    'material',
    'epic',
    'Особо острый коготь.',
    'boss_drop',
    '{"boss_types": ["hunter_spider"], "drop_locations": ["hunting_grounds", "predator_lair"]}',
    '/src/assets/items/hunter_claw.png',
    500,
    10,
    0.12
  ),
  (
    'silk_core',
    'Сердцевина шелка',
    'material',
    'legendary',
    'Чистейшая, магически усиленная паутина.',
    'boss_drop',
    '{"boss_types": ["silk_weaver"], "drop_locations": ["web_sanctum", "silk_chambers"]}',
    '/src/assets/items/silk_core.png',
    1000,
    18,
    0.03
  ),
  (
    'enhanced_guardian_chitin',
    'Усиленный хитин стражи',
    'material',
    'legendary',
    'Бронированная пластина с золотистым отливом.',
    'boss_drop',
    '{"boss_types": ["guardian_spider"], "drop_locations": ["guardian_temple", "golden_caves"]}',
    '/src/assets/items/enhanced_guardian_chitin.png',
    1200,
    20,
    0.02
  ),
  (
    'queen_larva_stinger',
    'Жало королевы-личинки',
    'material',
    'rare',
    'Маленькое, но невероятно ядовитое.',
    'boss_drop',
    '{"boss_types": ["queen_larva"], "drop_locations": ["hive_chambers", "nursery_caves"]}',
    '/src/assets/items/queen_larva_stinger.png',
    400,
    8,
    0.15
  ),
  (
    'concentrated_poison_gland',
    'Железа концентрированного яда',
    'material',
    'epic',
    'Для создания мощных ядов.',
    'boss_drop',
    '{"boss_types": ["poison_master"], "drop_locations": ["toxic_pools", "poison_chambers"]}',
    '/src/assets/items/concentrated_poison_gland.png',
    650,
    13,
    0.07
  ),
  (
    'ancient_hermit_eye',
    'Око древнего отшельника',
    'material',
    'legendary',
    'Видит сквозь время и иллюзии.',
    'boss_drop',
    '{"boss_types": ["ancient_hermit"], "drop_locations": ["time_rift", "ancient_sanctum"]}',
    '/src/assets/items/ancient_hermit_eye.png',
    1500,
    25,
    0.01
  ),
  (
    'shadow_web_gland',
    'Тенетная железа',
    'material',
    'legendary',
    'Создает паутину, поглощающую свет.',
    'boss_drop',
    '{"boss_types": ["shadow_weaver"], "drop_locations": ["shadow_realm", "dark_nexus"]}',
    '/src/assets/items/shadow_web_gland.png',
    1300,
    22,
    0.02
  );