-- Добавляем 8 новых предметов Арахны в таблицу item_templates
INSERT INTO public.item_templates (
  item_id, name, type, rarity, description, stats, source_type, image_url, drop_chance, level_requirement, value, slot
) VALUES 
(
  'archmage_soul_shard',
  'Осколок души Архимага',
  'material', 
  'legendary',
  'Концентрированная магическая энергия для зачарования',
  '{"power": 25, "magicResistance": 15}',
  'boss_drop',
  '/src/assets/items/archmage_soul_shard.png',
  0.02,
  50,
  10000,
  null
),
(
  'progenitor_heart',
  'Сердце Прародительницы', 
  'material',
  'legendary',
  'Бьющееся сердце, источник жизни всей колонии',
  '{"health": 500, "regeneration": 10}',
  'boss_drop',
  '/src/assets/items/progenitor_heart.png',
  0.01,
  60,
  15000,
  null
),
(
  'arachne_silk_gland',
  'Брюшная железа Арахны',
  'material',
  'epic', 
  'Источник неиссякаемого шелка высшего качества',
  '{"crafting": 20, "durability": 50}',
  'boss_drop',
  '/src/assets/items/arachne_silk_gland.png',
  0.05,
  40,
  5000,
  null
),
(
  'progenitor_egg',
  'Яйцо Прародительницы',
  'consumable',
  'legendary',
  'Легендарный предмет. Можно приготовить легендарные блюда',
  '{"nutrition": 100, "experience": 1000}',
  'boss_drop', 
  '/src/assets/items/progenitor_egg.png',
  0.01,
  55,
  20000,
  null
),
(
  'primas_eye',
  'Глаз Примаса',
  'accessory',
  'legendary',
  'Видит сущность всех живых существ, дает проницательность',
  '{"perception": 50, "criticalChance": 25}',
  'boss_drop',
  '/src/assets/items/primas_eye.png',
  0.02,
  65,
  12000,
  'neck'
),
(
  'arachne_claw',
  'Лапа Арахны',
  'weapon',
  'legendary',
  'Острое как бритва копье, оставшееся от древней богини',
  '{"power": 120, "piercing": 40, "poison": 15}',
  'boss_drop',
  '/src/assets/items/arachne_claw.png',
  0.03,
  50,
  8000,
  'weapon'
),
(
  'arachne_crown',
  'Венец Арахны',
  'armor',
  'legendary',
  'Тиара, дающая полный контроль над паукообразными существами',
  '{"power": 60, "commandAura": 30, "mentalResistance": 25}',
  'boss_drop',
  '/src/assets/items/arachne_crown.png', 
  0.015,
  70,
  18000,
  'head'
),
(
  'ashen_threads_cloak',
  'Плащ из пепельных нитей',
  'armor',
  'epic',
  'Плащ, дающий сопротивление магии',
  '{"defense": 45, "magicResistance": 60, "stealth": 20}',
  'boss_drop',
  '/src/assets/items/ashen_threads_cloak.png',
  0.04,
  45,
  6000,
  'chest'
);