-- Add spider-related items to item_templates table
INSERT INTO item_templates (
  item_id, name, type, rarity, description, source_type, source_details, 
  image_url, value, level_requirement, drop_chance
) VALUES 
  (
    'spider_silk',
    'Паучий шелк',
    'material',
    'common',
    'Прочная, эластичная нить. Основа для многих рецептов.',
    'monster_drop',
    '{"monster_types": ["spider"], "drop_locations": ["spider_cave", "dark_forest"]}',
    '/src/assets/items/spider_silk.png',
    25,
    1,
    0.45
  ),
  (
    'spider_poison_small',
    'Яд паука (малый флакон)',
    'consumable',
    'common',
    'Зеленоватая токсичная жидкость.',
    'monster_drop',
    '{"monster_types": ["spider"], "drop_locations": ["spider_cave", "dark_forest"]}',
    '/src/assets/items/spider_poison.jpg',
    50,
    3,
    0.30
  ),
  (
    'spider_fang',
    'Клык паука',
    'material',
    'uncommon',
    'Острый и прочный. Используется для создания кинжалов, наконечников стрел.',
    'monster_drop',
    '{"monster_types": ["spider"], "drop_locations": ["spider_cave", "dark_forest"]}',
    '/src/assets/items/spider_fang.png',
    100,
    5,
    0.25
  ),
  (
    'spider_eye',
    'Глаз паука',
    'material',
    'uncommon',
    'Слегка светящийся в темноте. Используется в алхимии.',
    'monster_drop',
    '{"monster_types": ["spider"], "drop_locations": ["spider_cave", "dark_forest"]}',
    '/src/assets/items/spider_eye.png',
    75,
    4,
    0.35
  ),
  (
    'chelicerae',
    'Хелицеры',
    'material',
    'rare',
    'Клешнеобразные челюсти.',
    'monster_drop',
    '{"monster_types": ["spider"], "drop_locations": ["spider_cave", "deep_caverns"]}',
    '/src/assets/items/chelicerae.png',
    200,
    8,
    0.15
  ),
  (
    'chitin_fragment',
    'Фрагмент хитина',
    'material',
    'common',
    'Мелкие осколки хитина.',
    'monster_drop',
    '{"monster_types": ["spider", "insect"], "drop_locations": ["spider_cave", "forest"]}',
    '/src/assets/items/chitin_fragment.png',
    35,
    2,
    0.50
  ),
  (
    'spider_limbs',
    'Конечности паука',
    'material',
    'uncommon',
    'Из них можно извлечь сухожилия и другие полезные материалы.',
    'monster_drop',
    '{"monster_types": ["spider"], "drop_locations": ["spider_cave", "dark_forest"]}',
    '/src/assets/items/spider_limbs.png',
    90,
    6,
    0.20
  ),
  (
    'spider_tendons',
    'Сухожилие паука',
    'material',
    'rare',
    'Прочное волокно для тетивы и усилителей брони.',
    'crafting',
    '{"requires": ["spider_limbs"], "craft_locations": ["crafting_table", "alchemy_table"]}',
    '/src/assets/items/spider_tendons.png',
    150,
    7,
    null
  ),
  (
    'poison_gland',
    'Железа яда',
    'material',
    'rare',
    'Орган, вырабатывающий яд. Более концентрирован, чем малый флакон.',
    'monster_drop',
    '{"monster_types": ["spider"], "drop_locations": ["spider_cave", "deep_caverns"]}',
    '/src/assets/items/poison_gland.png',
    300,
    10,
    0.10
  ),
  (
    'spider_eggs',
    'Паучьи яйца',
    'consumable',
    'uncommon',
    'Используются в кулинарии или алхимии.',
    'monster_drop',
    '{"monster_types": ["spider"], "drop_locations": ["spider_cave", "spider_nest"]}',
    '/src/assets/items/spider_eggs.png',
    80,
    5,
    0.20
  );