// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rovamdzzbjyyxjxestql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdmFtZHp6Ymp5eXhqeGVzdHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODE0MjAsImV4cCI6MjA3Mzk1NzQyMH0.M3FvSUH9PoqqwfYeHheIXjY4OCsQTInVZPRo_zpfpqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});